apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260510-155109-zas8nokddu7x-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260510-155109-zas8nokddu7x.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260510-155109-zas8nokddu7x-service
            port:
              number: 80
